### ISSUE TITLE
First step. React frm tutorial

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-11#1]
https://medium.com/quick-code/lets-learn-react-chapter-1-setting-up-environment-e9505b6644

after reading each chapter you need to push your code updates here and also give me a short resume about what exactly did you. it'll needed for better understanding your progress

**Comment by atherdon** [comment]
and a lot of importnant info are : https://medium.com/groceristar/things-that-should-read-and-use-javascript-intern-at-groceristar-april-18-collection-bd6541e9ae28

**Comment by atherdon** [comment]
@poojashukla10 if something will be not clear - tell me

**Comment by atherdon** [comment]
yes, you need to read that article - this was the reason why i add it here :)

**Comment by atherdon** [comment]
specify your question and i'll explain

**Comment by poojashukla10** [comment]
hi i have gone through all articles which you shared, java script , html, css seems okay, but i couldn't download loopback, right now I am looking at react.js on plural website, doyou want me to give any task for development?

**Comment by poojashukla10** [comment]
I am available all 7 days

**Comment by atherdon** [comment]
right now i want to see how you'll work on this react tutorial. it's pretty good and it have at least 10 chapters.
so i want to see your code on this repository that will be similar to code from that chapters. later, when i'll understand your abilities - you'll be assigned a real task. @poojashukla10

**Comment by poojashukla10** [comment]
okay I will take few more days then

**Comment by poojashukla10** [comment]
could you please provide me exact link, from where i can get react js
 content. I can see just this . I read what ever is available in link.
Testing

   - *Jest Tutorials and Insights*
   <https://www.codementor.io/community/topic/jest>
   - *How to Test React Components Using Jest*
   <https://www.sitepoint.com/test-react-components-jest/>
   - *Jest Official Documentation*
   <https://facebook.github.io/jest/docs/en/getting-started.html>
   - *Testing React Apps*
   <https://facebook.github.io/jest/docs/en/tutorial-react.html>
   - *API testing with Jest
   <https://hackernoon.com/api-testing-with-jest-d1ab74005c0a>*

https://medium.com/groceristar/things-that-should-read-and-use-javascript-intern-at-groceristar-april-18-collection-bd6541e9ae28

**Comment by atherdon** [comment]
testing is not important for you at this moment. but it's good that you read about the basics.

yeah i can share to you link with react stuff. you can see it in task description.
i can duplicate it again, if you wish. btw, don't forget to commit code frequently. it's important because - i'll see that you're familiar with git/bithub or not, i'll see that you're trying code samples from tutorials, and if you'll catch a bug(read when) i'll be able to take a look and try to help you.
so please at least one code commit per day @poojashukla10

**Comment by poojashukla10** [comment]
yes please  provide me react stuff link

**Comment by atherdon** [comment]
i assign a new task for you, for making things more understandable

**Comment by poojashukla10** [comment]
i uploaded one, i will complete most of them bySunday,  I work here part
time but I am maximum time in coding. soon you will get second
